aptos/api/aux-ts/src/graphql/client/assets/index.5d9ae928.js, aptos/api/aux-ts/src/graphql/client/index.html, aptos/api/aux-ts/src/graphql/index.ts, aptos/api/aux-ts/tsconfig.json
Update FE bundle to reference PoolCoins for CoinXY params used by swap, pool, add/remove liq UI
=> chore: update fe bundle

aptos/api/aux-ts/src/amm/core/events.ts, aptos/api/aux-ts/src/clob/core/events.ts, aptos/api/aux-ts/test/clob.spec.ts, aptos/contract/aux/sources/clob_market.move, aptos/contract/aux/sources/fee.move, aptos/contract/aux/sources/router.move, aptos/contract/aux/sources/vault.move, aptos/contract/aux/sources/volume_tracker.move
Leaving vault as `u128` since theoretically values can be greater than max `Coin` balance with leverage
=> chore(aux): small clean-ups/optimizations in CLOB

aptos/abort-only-contract/aux/sources/clob_market.move, aptos/contract/aux/sources/clob_market.move
Cannot change data structure of deployed code.
=> fix(aux): remove incompatibility

aptos/contract/aux/sources/clob_market.move
=> feat(aux): transfer net fees to @aux

README.md, aptos/api/aux-ts/test/clob.spec.ts, aptos/contract/aux/sources/clob_market.move, aptos/contract/aux/sources/fee.move
End to end and aptos move tests pass
=> feat(aux): zero fees

aptos/contract/aux/sources/clob_market.move
This reverts commit d72f9ed1a1ba36ede909f149fc554f5450f94883.
=> Revert "chore(aux): hide friend functions from public"

aptos/api/aux-ts/examples/devnet-fund-fake-coins.ts
=> example(aux-ts): helper to fund fake coins

aptos/api/aux-ts/examples/mainnet-market-structure.ts
Example script for market makers to scrape pool and CLOB metadata.
=> example(aux): query pool and market metadata

aptos/api/aux-ts/src/coins.ts, aptos/api/aux-ts/src/graphql/generated/types.ts, aptos/api/aux-ts/src/graphql/resolvers/query.ts, aptos/api/aux-ts/src/graphql/typeDefs/pool.graphql
Add featured status to pools. Sort by hot status, recognized USD stablecoin liquidity, and atomic units of liquidity.
=> feat(graphql): sort pools by liquidity, featured

aptos/api/aux-ts/src/graphql/resolvers/query.ts
Return coins by feature priority, then recognized liquidity, then au liquidity. This is similar to pool sort order.
=> feat(graphql): return coins in roughly pool order

aptos/api/aux-ts/src/amm/core/query.ts, aptos/api/aux-ts/src/client.ts
Defaults to querying one RPC call worth (100 most recent events) in the pool, but provide options to change the start or the limit by stitching multiple queries.
Tested manually.
=> feat(aux-ts): add event pagination options

aptos/api/aux-ts/analytics/pool-analytics.ts
=> feat(analytics): add script for pool statistics

aptos/abort-only-contract/aux/sources/amm.move, aptos/abort-only-contract/aux/sources/clob_market.move, aptos/abort-only-contract/aux/sources/fake_coin.move, aptos/abort-only-contract/aux/sources/fake_markets.move, aptos/abort-only-contract/aux/sources/fee.move, aptos/abort-only-contract/aux/sources/router.move, aptos/abort-only-contract/aux/sources/vault.move, aptos/contract/aux/Move.toml, aptos/contract/aux/sources/fake_coin.move
also include updates to the abort-only contract.
=> fix(aux): initialize fake coin during aptos test

aptos/api/aux-ts/src/graphql/resolvers/query.ts
=> chore(graphql): unfeature MOJO

aptos/api/aux-ts/src/graphql/resolvers/pool.ts
This reverts commit b2eabb8658a751b38ebe1439897bb5a06e6c6179.
=> Revert "fix(graphql): AMM price impact"

aptos/api/aux-ts/src/graphql/resolvers/pool.ts
=> fix(aux-ts): update price impact pct for quoteExactOut

Cargo.lock, aptos/abort-only-contract/aux/Move.toml, aptos/contract/deployer/Cargo.toml, aptos/contract/deployer/Move.toml, aptos/contract/deployer/src/bin/delete-code.rs, aptos/contract/util-for-aptos/Cargo.toml, aptos/contract/util-for-aptos/src/lib.rs, aptos/testing/base-container/Containerfile, go-util/aptos/cmd/check-aptos-version.go
also:
- add a binary to delete uploaded code
- up max gas to 500_000 (or 0.5 APT)
=> chore(aux-rust): update aptos to v1.0.1

aptos/api/aux-ts/src/graphql/resolvers/account.ts
Users may accidentally register a CoinStore on a type that isn't a registered coin. Filter those out.
Tested by standing up a graphql server and manually querying a problematic account.
=> fix(graphql): ignore invalid coins

Cargo.lock, aptos/abort-only-contract/aux/Move.toml, aptos/contract/deployer/Cargo.toml, aptos/contract/deployer/Move.toml, aptos/contract/util-for-aptos/Cargo.toml, aptos/contract/util-for-aptos/src/lib.rs, aptos/testing/base-container/Containerfile, go-util/aptos/cmd/check-aptos-version.go
This reverts commit 497f95b5431626876ee7a3613e81b96d014c2108.
=> Revert "chore(aux-rust): update aptos to v1.0.1 (#251)"

aptos/api/aux-ts/src/account.ts, aptos/api/aux-ts/src/clob/core/query.ts, aptos/api/aux-ts/src/clob/dsl/market.ts, aptos/api/aux-ts/src/graphql/conversion.ts, aptos/api/aux-ts/src/graphql/resolvers/account.ts, aptos/api/aux-ts/src/graphql/resolvers/market.ts, aptos/api/aux-ts/src/indexer/index.ts
=> fix(ts): #224 cancelled order displayed as open still

CONTRIBUTING.md, aptos/api/aux-ts/src/graphql/generated/types.ts, aptos/api/aux-ts/src/graphql/resolvers/query.ts, aptos/api/aux-ts/src/graphql/typeDefs/constant-product.graphql, aptos/api/aux-ts/src/graphql/typeDefs/schema.graphql, aptos/api/aux-ts/src/pool/schema.ts
=> feat(graphql): attach versions to events

aptos/abort-only-contract/aux/sources/authority.move, aptos/abort-only-contract/aux/sources/stake.move, aptos/contract/aux/sources/authority.move, aptos/contract/aux/sources/stake.move
Yield farming implementation based on SushiSwap's Masterchef contract.
=> feat(aux): simple yield farming contract (masterchef)

aptos/api/aux-ts/src/pool/stable-swap/client.ts, aptos/api/aux-ts/src/pool/stable-swap/schema.ts
-create pool / add and remove liquidity.
=> feat(api): stable swap create pool / add and remove liquidity

aptos/api/aux-ts/src/graphql/client.ts, aptos/api/aux-ts/src/graphql/resolvers/market.ts
This reverts commit eedaf64a4c28605ba9e32239de86f046460e76b8.
=> Revert "fix(graphql): replace serum rpc node"
